# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6403bb2129a7bcec164b92c272da7d37e4b5465d4d2d019017f121523636f007f2c3c38ac2ea896d0f1399d67ed7206ff5280d4fab97f02da4432150ce4ab2c7

test:
  secret_key_base: 4a840c20cffe24ee37d3a2da69dcf0e789a304701136c936217a2f45ede7f7ec891c7b50f0752d2cdefc9f1deae5396c1102be6d8dbcb6837a88e853088212a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
